/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package W14B_G4_Assignment2;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
}
